spring.application.name=health-monitor

# Server configuration
server.port=8080

# Actuator configuration
#management.endpoints.web.exposure.include=health,info
management.endpoints.web.exposure.include=health,info,beans,metrics,loggers
management.endpoint.health.show-details=always

# External service URL for health check (using a mock service)
#external.service.url=https://httpbin.org/status/200
external.service.url=http://localhost:8080/cutomer
