spring.application.name=basics-di

#payment.provider=stripe
#spring.profiles.active=razor			# simple case requiring no additional annotations
spring.profiles.active=razor,stripe		# Primary and Qualifier